-- NevGenç üretim güvenliği
-- Amaç: gerçek e-posta/parola Auth, sunucu tarafı kayıt kısıtı, rol ayrımı,
-- RLS sertleştirmesi, kullanıcı verisi bütünlüğü ve yönetici limitleri.
-- Bu dosyada service_role anahtarı yoktur ve hiçbir zaman frontend'e konulmamalıdır.

create extension if not exists pgcrypto;
create schema if not exists private;

-- -----------------------------------------------------------------------------
-- 1) Kurumlar ve rol ilişkileri
-- -----------------------------------------------------------------------------
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null check (slug ~ '^[a-z0-9-]{2,80}$'),
  name text not null check (char_length(name) between 2 and 120),
  type text not null check (type in ('university','municipality','other')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.organizations (slug,name,type) values
  ('sakarya-universitesi','Sakarya Üniversitesi','university'),
  ('serdivan-belediyesi','Serdivan Belediyesi','municipality')
on conflict (slug) do update set name=excluded.name,type=excluded.type,is_active=true;

create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  added_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.community_admins (
  community_id uuid not null references public.communities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  added_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (community_id,user_id)
);
create index if not exists community_admins_user_idx on public.community_admins(user_id);

create table if not exists public.organization_editors (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  added_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (organization_id,user_id)
);
create index if not exists organization_editors_user_idx on public.organization_editors(user_id);

-- Kural dışı/özel hesaplar için manuel izin listesi. Public istemci okuyamaz.
create table if not exists public.auth_signup_allowlist (
  email text primary key check (email = lower(email) and char_length(email) <= 160),
  note text check (note is null or char_length(note) <= 300),
  created_at timestamptz not null default now()
);

create table if not exists public.content_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 2 and 80),
  entity_type text not null check (char_length(entity_type) between 2 and 80),
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists content_audit_actor_idx on public.content_audit_log(actor_id,created_at desc);

alter table public.announcements add column if not exists organization_id uuid references public.organizations(id) on delete set null;
alter table public.announcements add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.announcements add column if not exists updated_by uuid references auth.users(id) on delete set null;
create index if not exists announcements_organization_idx on public.announcements(organization_id);

-- E-posta kullanıcıya ait profil satırında yalnızca sunucu tarafından tutulur.
-- Bu, Edge Function'ın auth.users şemasını dışarı açmadan hedef hesabı bulmasını sağlar.
alter table public.profiles add column if not exists email_lower text;
create unique index if not exists profiles_email_lower_unique on public.profiles(email_lower) where email_lower is not null;
update public.profiles p
set email_lower=lower(u.email)
from auth.users u
where p.id=u.id and u.email is not null and p.email_lower is distinct from lower(u.email);

-- -----------------------------------------------------------------------------
-- 2) RLS içinde kullanılan PRIVATE güvenlik yardımcıları
-- Public Data API üzerinden RPC olarak çağrılamazlar.
-- -----------------------------------------------------------------------------
create or replace function private.is_platform_admin(p_user_id uuid default auth.uid())
returns boolean
language sql stable security definer set search_path=''
as $$
  select p_user_id is not null
     and exists(select 1 from public.platform_admins p where p.user_id=p_user_id)
$$;

create or replace function private.is_community_admin(p_community_id uuid,p_user_id uuid default auth.uid())
returns boolean
language sql stable security definer set search_path=''
as $$
  select p_user_id is not null and p_community_id is not null
     and exists(select 1 from public.community_admins a where a.community_id=p_community_id and a.user_id=p_user_id)
$$;

create or replace function private.is_organization_editor(p_organization_id uuid,p_user_id uuid default auth.uid())
returns boolean
language sql stable security definer set search_path=''
as $$
  select p_user_id is not null and p_organization_id is not null
     and exists(select 1 from public.organization_editors e where e.organization_id=p_organization_id and e.user_id=p_user_id)
$$;

create or replace function private.is_allowed_app_user(p_user_id uuid default auth.uid())
returns boolean
language plpgsql stable security definer set search_path=''
as $$
declare v_email text;
begin
  if p_user_id is null then return false; end if;
  select lower(email) into v_email from auth.users where id=p_user_id;
  if v_email is null then return false; end if;

  -- SAÜ öğrenci hesabı
  if v_email ~ '^[^@[:space:]]+@ogr\.sakarya\.edu\.tr$' then return true; end if;
  -- SUBÜ öğrenci hesabı (kurumun yayımladığı örnek biçim)
  if v_email ~ '^g[0-9]+@subu\.edu\.tr$' then return true; end if;
  -- Kurum editörü olarak daha sonra rol atanabilecek kurumsal hesaplar
  if v_email ~ '^[^@[:space:]]+@(sakarya\.edu\.tr|serdivan\.bel\.tr)$' then return true; end if;
  if exists(select 1 from public.auth_signup_allowlist a where a.email=v_email) then return true; end if;

  -- Daha önce rol atanmış hesaplar, domain politikası sonradan değişse dahi kilitlenmez.
  if private.is_platform_admin(p_user_id) then return true; end if;
  if exists(select 1 from public.community_admins a where a.user_id=p_user_id) then return true; end if;
  if exists(select 1 from public.organization_editors e where e.user_id=p_user_id) then return true; end if;
  return false;
end $$;

revoke all on schema private from public;
grant usage on schema private to authenticated;
revoke all on function private.is_platform_admin(uuid) from public;
revoke all on function private.is_community_admin(uuid,uuid) from public;
revoke all on function private.is_organization_editor(uuid,uuid) from public;
revoke all on function private.is_allowed_app_user(uuid) from public;
grant execute on function private.is_platform_admin(uuid) to authenticated;
grant execute on function private.is_community_admin(uuid,uuid) to authenticated;
grant execute on function private.is_organization_editor(uuid,uuid) to authenticated;
grant execute on function private.is_allowed_app_user(uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- 3) Supabase Before User Created Hook
-- Dashboard > Authentication > Hooks bölümünde private.hook_restrict_signup seçilmelidir.
-- İzinli ise {} döner; aksi durumda kayıt Auth tablosuna hiç yazılmaz.
-- -----------------------------------------------------------------------------
create or replace function private.hook_restrict_signup(event jsonb)
returns jsonb
language plpgsql stable security definer set search_path=''
as $$
declare v_email text;
begin
  v_email:=lower(coalesce(event->'user'->>'email',''));
  if v_email ~ '^[^@[:space:]]+@ogr\.sakarya\.edu\.tr$'
     or v_email ~ '^g[0-9]+@subu\.edu\.tr$'
     or v_email ~ '^[^@[:space:]]+@(sakarya\.edu\.tr|serdivan\.bel\.tr)$'
     or exists(select 1 from public.auth_signup_allowlist a where a.email=v_email) then
    return '{}'::jsonb;
  end if;
  return jsonb_build_object(
    'error',jsonb_build_object(
      'http_code',403,
      'message','NevGenç kaydı yalnızca yetkili öğrenci veya kurum e-posta adresleriyle açılabilir.'
    )
  );
end $$;

grant usage on schema private to supabase_auth_admin;
revoke all on function private.hook_restrict_signup(jsonb) from public,anon,authenticated;
grant execute on function private.hook_restrict_signup(jsonb) to supabase_auth_admin;

-- Auth kayıtlarında profil oluşturma işlemini public SECURITY DEFINER fonksiyondan private şemaya taşı.
create or replace function private.handle_new_user()
returns trigger
language plpgsql security definer set search_path=''
as $$
begin
  insert into public.profiles(id,full_name,email_lower)
  values(
    new.id,
    left(nullif(regexp_replace(coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name',''),'\\s+',' ','g'),''),80),
    lower(new.email)
  )
  on conflict(id) do update set email_lower=excluded.email_lower;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function private.handle_new_user();

-- -----------------------------------------------------------------------------
-- 4) Yönetici sayısı limitleri (eş zamanlı isteklerde de aşılmasın)
-- -----------------------------------------------------------------------------
create or replace function private.enforce_platform_admin_limit()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  perform pg_advisory_xact_lock(hashtextextended('nevgenc-platform-admin-limit',0));
  if (select count(*) from public.platform_admins) >= 4 then
    raise exception 'Platform yöneticisi limiti 4 kişidir.' using errcode='P0001';
  end if;
  return new;
end $$;

drop trigger if exists trg_platform_admin_limit on public.platform_admins;
create trigger trg_platform_admin_limit before insert on public.platform_admins
for each row execute function private.enforce_platform_admin_limit();

create or replace function private.enforce_community_admin_limit()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  perform pg_advisory_xact_lock(hashtextextended('nevgenc-community-'||new.community_id::text,0));
  if (select count(*) from public.community_admins where community_id=new.community_id) >= 4 then
    raise exception 'Bir toplulukta en fazla 4 yönetici olabilir.' using errcode='P0001';
  end if;
  return new;
end $$;

drop trigger if exists trg_community_admin_limit on public.community_admins;
create trigger trg_community_admin_limit before insert on public.community_admins
for each row execute function private.enforce_community_admin_limit();

-- -----------------------------------------------------------------------------
-- 5) Kullanıcı verisi bütünlüğü
-- -----------------------------------------------------------------------------
revoke update on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant update (full_name,university,department,avatar_url,updated_at) on public.profiles to authenticated;

-- Kullanıcı kendi email_lower veya n_points değerini değiştiremez.
drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select to authenticated
using ((select auth.uid())=id);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update safe profile fields" on public.profiles for update to authenticated
using ((select auth.uid())=id and private.is_allowed_app_user((select auth.uid())))
with check ((select auth.uid())=id and private.is_allowed_app_user((select auth.uid())));

-- -----------------------------------------------------------------------------
-- 6) Takip, etkinlik tercihi ve kütüphane RLS sertleştirmesi
-- -----------------------------------------------------------------------------
grant select,insert,delete on public.community_follows to authenticated;
grant select,insert,update,delete on public.announcement_responses to authenticated;
grant select,insert,update on public.library_reservations to authenticated;

drop policy if exists "users read own community follows" on public.community_follows;
drop policy if exists "users create own community follows" on public.community_follows;
drop policy if exists "users delete own community follows" on public.community_follows;
drop policy if exists "allowed users create own community follows" on public.community_follows;
drop policy if exists "allowed users delete own community follows" on public.community_follows;
create policy "allowed users read own community follows" on public.community_follows for select to authenticated
using ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));
create policy "allowed users create own community follows" on public.community_follows for insert to authenticated
with check ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));
create policy "allowed users delete own community follows" on public.community_follows for delete to authenticated
using ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));

drop policy if exists "users read own announcement responses" on public.announcement_responses;
drop policy if exists "users create own announcement responses" on public.announcement_responses;
drop policy if exists "users update own announcement responses" on public.announcement_responses;
drop policy if exists "users delete own announcement responses" on public.announcement_responses;
drop policy if exists "allowed users create own announcement responses" on public.announcement_responses;
drop policy if exists "allowed users update own announcement responses" on public.announcement_responses;
drop policy if exists "allowed users delete own announcement responses" on public.announcement_responses;
create policy "allowed users read own announcement responses" on public.announcement_responses for select to authenticated
using ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));
create policy "allowed users create own announcement responses" on public.announcement_responses for insert to authenticated
with check ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));
create policy "allowed users update own announcement responses" on public.announcement_responses for update to authenticated
using ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())))
with check ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));
create policy "allowed users delete own announcement responses" on public.announcement_responses for delete to authenticated
using ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));

drop policy if exists "users read own reservations" on public.library_reservations;
drop policy if exists "users create own reservations" on public.library_reservations;
drop policy if exists "users update own reservations" on public.library_reservations;
drop policy if exists "allowed users create own reservations" on public.library_reservations;
drop policy if exists "allowed users update own reservations" on public.library_reservations;
create policy "allowed users read own reservations" on public.library_reservations for select to authenticated
using ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));
create policy "allowed users create own reservations" on public.library_reservations for insert to authenticated
with check ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));
create policy "allowed users update own reservations" on public.library_reservations for update to authenticated
using ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())))
with check ((select auth.uid())=user_id and private.is_allowed_app_user((select auth.uid())));

create or replace function private.validate_library_reservation()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  if new.user_id<>(select auth.uid()) and not private.is_platform_admin((select auth.uid())) then
    raise exception 'Başka kullanıcı adına randevu oluşturamazsın.';
  end if;
  if new.status not in ('confirmed','cancelled','completed') then raise exception 'Geçersiz randevu durumu.'; end if;
  if tg_op='INSERT' and new.status<>'confirmed' then raise exception 'Yeni randevu confirmed durumunda oluşturulmalıdır.'; end if;
  if new.starts_at < now()-interval '5 minutes' then raise exception 'Geçmiş tarih için randevu oluşturulamaz.'; end if;
  if new.starts_at > now()+interval '45 days' then raise exception 'Randevu en fazla 45 gün ileriye alınabilir.'; end if;
  if new.ends_at-new.starts_at < interval '30 minutes' or new.ends_at-new.starts_at > interval '3 hours' then
    raise exception 'Randevu süresi 30 dakika ile 3 saat arasında olmalıdır.';
  end if;
  if not exists(select 1 from public.library_spaces s where s.id=new.space_id and s.is_active=true and s.reservable=true) then
    raise exception 'Bu çalışma alanı rezervasyona açık değil.';
  end if;
  if new.status='confirmed' and exists(
    select 1 from public.library_reservations r
    where r.user_id=new.user_id and r.status='confirmed'
      and r.id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid)
      and tstzrange(r.starts_at,r.ends_at,'[)') && tstzrange(new.starts_at,new.ends_at,'[)')
  ) then raise exception 'Bu saat aralığında başka bir randevun bulunuyor.'; end if;
  return new;
end $$;

drop trigger if exists trg_validate_library_reservation on public.library_reservations;
create trigger trg_validate_library_reservation before insert or update on public.library_reservations
for each row execute function private.validate_library_reservation();

-- -----------------------------------------------------------------------------
-- 7) Rol tabloları: istemciden yazma KAPALI. Yetkili yazma yalnızca Edge Function.
-- -----------------------------------------------------------------------------
alter table public.organizations enable row level security;
alter table public.platform_admins enable row level security;
alter table public.community_admins enable row level security;
alter table public.organization_editors enable row level security;
alter table public.auth_signup_allowlist enable row level security;
alter table public.content_audit_log enable row level security;

revoke all on public.platform_admins,public.community_admins,public.organization_editors,public.auth_signup_allowlist,public.content_audit_log from anon;
revoke insert,update,delete on public.platform_admins,public.community_admins,public.organization_editors,public.auth_signup_allowlist,public.content_audit_log from authenticated;
grant select on public.organizations to anon,authenticated;
grant select on public.platform_admins,public.community_admins,public.organization_editors to authenticated;

-- Yeniden çalıştırılabilirlik için aynı isimli politikaları temizle.
drop policy if exists "public read active organizations" on public.organizations;
drop policy if exists "platform admins read platform admins" on public.platform_admins;
drop policy if exists "users read relevant community admins" on public.community_admins;
drop policy if exists "users read own organization editor records" on public.organization_editors;
drop policy if exists "platform admins read audit" on public.content_audit_log;

create policy "public read active organizations" on public.organizations for select to anon,authenticated using(is_active=true);
create policy "platform admin membership visible to self" on public.platform_admins for select to authenticated
using(user_id=(select auth.uid()) or private.is_platform_admin((select auth.uid())));
create policy "community admin membership visible to relevant admins" on public.community_admins for select to authenticated
using(user_id=(select auth.uid()) or private.is_platform_admin((select auth.uid())) or private.is_community_admin(community_id,(select auth.uid())));
create policy "organization editor membership visible to self" on public.organization_editors for select to authenticated
using(user_id=(select auth.uid()) or private.is_platform_admin((select auth.uid())));
create policy "platform admins read audit" on public.content_audit_log for select to authenticated
using(private.is_platform_admin((select auth.uid())));
-- auth_signup_allowlist için SELECT politikası yoktur.

-- -----------------------------------------------------------------------------
-- 8) Public içerik: okuma açık, ayrıcalıklı yazma browser'dan kapalı.
-- Edge Functions service_role ile sunucu tarafında rol kontrolünden sonra yazar.
-- -----------------------------------------------------------------------------
grant select on public.communities,public.partners,public.map_locations,public.transport_lines,
  public.transport_stops,public.transport_line_stops,public.opportunities,public.dining_menus,
  public.dining_menu_items,public.library_spaces,public.announcements to anon,authenticated;

revoke insert,update,delete on public.announcements from anon,authenticated;
revoke insert,update,delete on public.communities,public.partners,public.map_locations,public.transport_lines,
  public.transport_stops,public.transport_line_stops,public.opportunities,public.dining_menus,
  public.dining_menu_items,public.library_spaces from anon,authenticated;

-- Topluluk takip sayısı: kişisel kimlik döndürmeden yalnızca toplu sayı verir.
-- SECURITY DEFINER hesaplama private şemadadır; public wrapper yalnızca agregayı döndürür.
create or replace function private.community_follow_counts()
returns table(slug text,follow_count bigint)
language sql stable security definer set search_path=''
as $$
  select c.slug,count(f.user_id)::bigint
  from public.communities c
  left join public.community_follows f on f.community_id=c.id
  where c.is_active=true
  group by c.id,c.slug
$$;
revoke all on function private.community_follow_counts() from public;
grant usage on schema private to anon,authenticated;
grant execute on function private.community_follow_counts() to anon,authenticated;

create or replace function public.public_community_follow_counts()
returns table(slug text,follow_count bigint)
language sql stable security invoker set search_path=''
as $$ select * from private.community_follow_counts() $$;
revoke all on function public.public_community_follow_counts() from public;
grant execute on function public.public_community_follow_counts() to anon,authenticated;

-- Önceki geliştirme sürümünde public SECURITY DEFINER RPC'leri oluşturulmuşsa dış erişimini kapat.
do $$
begin
  if to_regprocedure('public.assign_community_admin(text,text)') is not null then execute 'revoke all on function public.assign_community_admin(text,text) from public,anon,authenticated'; end if;
  if to_regprocedure('public.remove_community_admin(text,text)') is not null then execute 'revoke all on function public.remove_community_admin(text,text) from public,anon,authenticated'; end if;
  if to_regprocedure('public.assign_platform_admin(text)') is not null then execute 'revoke all on function public.assign_platform_admin(text) from public,anon,authenticated'; end if;
  if to_regprocedure('public.assign_organization_editor(text,text)') is not null then execute 'revoke all on function public.assign_organization_editor(text,text) from public,anon,authenticated'; end if;
  if to_regprocedure('public.editor_create_announcement(jsonb)') is not null then execute 'revoke all on function public.editor_create_announcement(jsonb) from public,anon,authenticated'; end if;
  if to_regprocedure('public.editor_unpublish_announcement(uuid)') is not null then execute 'revoke all on function public.editor_unpublish_announcement(uuid) from public,anon,authenticated'; end if;
end $$;

-- İlk platform yöneticisi yalnızca bir kez SQL Editor üzerinden atanır:
-- insert into public.platform_admins(user_id)
-- select id from auth.users where lower(email)=lower('SENIN_EPOSTAN');
