-- NevGenç v16 güvenlik sertleştirmesi
-- Edge Function rate-limit, public API yüzey kontrolü ve güvenli varsayılanlar.

create table if not exists public.edge_rate_limit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scope text not null check (char_length(scope) between 2 and 120),
  created_at timestamptz not null default now()
);
create index if not exists edge_rate_limit_lookup_idx on public.edge_rate_limit_events(user_id,scope,created_at desc);
alter table public.edge_rate_limit_events enable row level security;
revoke all on public.edge_rate_limit_events from anon,authenticated;

-- Yalnız service_role tarafından çağrılır. Exposed schema'da olsa da anon/auth execute açık değildir.
create or replace function public.security_rate_limit_check(
  p_user_id uuid,
  p_scope text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path=''
as $$
declare v_count integer;
begin
  if p_user_id is null or p_scope is null or char_length(p_scope)>120 then return false; end if;
  if p_limit < 1 or p_limit > 500 or p_window_seconds < 1 or p_window_seconds > 86400 then return false; end if;

  -- Aynı kullanıcı/scope için eşzamanlı limit aşımını engeller.
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_scope, 0));
  select count(*) into v_count
  from public.edge_rate_limit_events
  where user_id=p_user_id and scope=p_scope
    and created_at >= now() - make_interval(secs => p_window_seconds);
  if v_count >= p_limit then return false; end if;
  insert into public.edge_rate_limit_events(user_id,scope) values(p_user_id,p_scope);
  -- tabloyu küçük tut
  delete from public.edge_rate_limit_events where created_at < now()-interval '2 days';
  return true;
end $$;

revoke all on function public.security_rate_limit_check(uuid,text,integer,integer) from public,anon,authenticated;
grant execute on function public.security_rate_limit_check(uuid,text,integer,integer) to service_role;

-- Hassas tablolarda istemci yazma yetkisi olmadığını yeniden garanti et.
revoke insert,update,delete on public.platform_admins,public.community_admins,public.organization_editors,
  public.auth_signup_allowlist,public.content_audit_log,public.edge_rate_limit_events from anon,authenticated;

-- Güvenlik helper'larının search_path'i önceki migration'larda boş olarak pinlenmiştir.
-- Bu migration tekrar çalıştırılabilir ve mevcut veriyi silmez.
